"""add return_location and return_receiver to checkout_records

Revision ID: 2ec8fc27d0f6
Revises: 2b8bcb0d4c3f
Create Date: 2026-04-29 23:30:04.089612

"""

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "2ec8fc27d0f6"
down_revision: str | Sequence[str] | None = "2b8bcb0d4c3f"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("checkout_records", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "return_location", sqlmodel.sql.sqltypes.AutoString(), nullable=True
            )
        )
        batch_op.add_column(
            sa.Column(
                "return_receiver", sqlmodel.sql.sqltypes.AutoString(), nullable=True
            )
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("checkout_records", schema=None) as batch_op:
        batch_op.drop_column("return_receiver")
        batch_op.drop_column("return_location")

    # ### end Alembic commands ###
