"""m1_initial_schema_baseline

Revision ID: 492867df5ecb
Revises:
Create Date: 2026-04-26 21:49:49.273157

"""

from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "492867df5ecb"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
