"""v4 asset brand column

Revision ID: b45ebfc4afe2
Revises: 2d589d84e584
Create Date: 2026-05-20 13:05:32.104154

"""

import json
from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel  # noqa: F401
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b45ebfc4afe2"
down_revision: str | Sequence[str] | None = "2d589d84e584"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("assets", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("brand", sqlmodel.sql.sqltypes.AutoString(), nullable=True)
        )
        batch_op.create_index(batch_op.f("ix_assets_brand"), ["brand"], unique=False)

    # ### end Alembic commands ###

    # 数据回填：custom_data.brand → 顶层 brand（仅当顶层 brand 为 null 且 custom_data.brand 非空字符串）
    bind = op.get_bind()
    rows = bind.execute(
        sa.text(
            "SELECT id, custom_data FROM assets "
            "WHERE brand IS NULL AND custom_data IS NOT NULL"
        )
    ).all()
    for asset_id, custom_data_str in rows:
        if not custom_data_str:
            continue
        try:
            cd = (
                json.loads(custom_data_str)
                if isinstance(custom_data_str, str)
                else custom_data_str
            )
        except (json.JSONDecodeError, TypeError):
            continue
        if not isinstance(cd, dict):
            continue
        brand_val = cd.get("brand")
        if isinstance(brand_val, str) and brand_val.strip():
            bind.execute(
                sa.text("UPDATE assets SET brand = :b WHERE id = :id"),
                {"b": brand_val, "id": asset_id},
            )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("assets", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_assets_brand"))
        batch_op.drop_column("brand")

    # ### end Alembic commands ###
