/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TypesRouteImport } from './routes/types'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TypesNewRouteImport } from './routes/types.new'
import { Route as TypesIdRouteImport } from './routes/types.$id'
import { Route as AssetsNewRouteImport } from './routes/assets.new'
import { Route as AssetsIdRouteImport } from './routes/assets.$id'
import { Route as AssetsIdIndexRouteImport } from './routes/assets.$id.index'
import { Route as AssetsIdEditRouteImport } from './routes/assets.$id.edit'

const TypesRoute = TypesRouteImport.update({
  id: '/types',
  path: '/types',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TypesNewRoute = TypesNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => TypesRoute,
} as any)
const TypesIdRoute = TypesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => TypesRoute,
} as any)
const AssetsNewRoute = AssetsNewRouteImport.update({
  id: '/assets/new',
  path: '/assets/new',
  getParentRoute: () => rootRouteImport,
} as any)
const AssetsIdRoute = AssetsIdRouteImport.update({
  id: '/assets/$id',
  path: '/assets/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AssetsIdIndexRoute = AssetsIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AssetsIdRoute,
} as any)
const AssetsIdEditRoute = AssetsIdEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => AssetsIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/types': typeof TypesRouteWithChildren
  '/assets/$id': typeof AssetsIdRouteWithChildren
  '/assets/new': typeof AssetsNewRoute
  '/types/$id': typeof TypesIdRoute
  '/types/new': typeof TypesNewRoute
  '/assets/$id/edit': typeof AssetsIdEditRoute
  '/assets/$id/': typeof AssetsIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/types': typeof TypesRouteWithChildren
  '/assets/new': typeof AssetsNewRoute
  '/types/$id': typeof TypesIdRoute
  '/types/new': typeof TypesNewRoute
  '/assets/$id/edit': typeof AssetsIdEditRoute
  '/assets/$id': typeof AssetsIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/types': typeof TypesRouteWithChildren
  '/assets/$id': typeof AssetsIdRouteWithChildren
  '/assets/new': typeof AssetsNewRoute
  '/types/$id': typeof TypesIdRoute
  '/types/new': typeof TypesNewRoute
  '/assets/$id/edit': typeof AssetsIdEditRoute
  '/assets/$id/': typeof AssetsIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/types'
    | '/assets/$id'
    | '/assets/new'
    | '/types/$id'
    | '/types/new'
    | '/assets/$id/edit'
    | '/assets/$id/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/types'
    | '/assets/new'
    | '/types/$id'
    | '/types/new'
    | '/assets/$id/edit'
    | '/assets/$id'
  id:
    | '__root__'
    | '/'
    | '/types'
    | '/assets/$id'
    | '/assets/new'
    | '/types/$id'
    | '/types/new'
    | '/assets/$id/edit'
    | '/assets/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  TypesRoute: typeof TypesRouteWithChildren
  AssetsIdRoute: typeof AssetsIdRouteWithChildren
  AssetsNewRoute: typeof AssetsNewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/types': {
      id: '/types'
      path: '/types'
      fullPath: '/types'
      preLoaderRoute: typeof TypesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/types/new': {
      id: '/types/new'
      path: '/new'
      fullPath: '/types/new'
      preLoaderRoute: typeof TypesNewRouteImport
      parentRoute: typeof TypesRoute
    }
    '/types/$id': {
      id: '/types/$id'
      path: '/$id'
      fullPath: '/types/$id'
      preLoaderRoute: typeof TypesIdRouteImport
      parentRoute: typeof TypesRoute
    }
    '/assets/new': {
      id: '/assets/new'
      path: '/assets/new'
      fullPath: '/assets/new'
      preLoaderRoute: typeof AssetsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assets/$id': {
      id: '/assets/$id'
      path: '/assets/$id'
      fullPath: '/assets/$id'
      preLoaderRoute: typeof AssetsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assets/$id/': {
      id: '/assets/$id/'
      path: '/'
      fullPath: '/assets/$id/'
      preLoaderRoute: typeof AssetsIdIndexRouteImport
      parentRoute: typeof AssetsIdRoute
    }
    '/assets/$id/edit': {
      id: '/assets/$id/edit'
      path: '/edit'
      fullPath: '/assets/$id/edit'
      preLoaderRoute: typeof AssetsIdEditRouteImport
      parentRoute: typeof AssetsIdRoute
    }
  }
}

interface TypesRouteChildren {
  TypesIdRoute: typeof TypesIdRoute
  TypesNewRoute: typeof TypesNewRoute
}

const TypesRouteChildren: TypesRouteChildren = {
  TypesIdRoute: TypesIdRoute,
  TypesNewRoute: TypesNewRoute,
}

const TypesRouteWithChildren = TypesRoute._addFileChildren(TypesRouteChildren)

interface AssetsIdRouteChildren {
  AssetsIdEditRoute: typeof AssetsIdEditRoute
  AssetsIdIndexRoute: typeof AssetsIdIndexRoute
}

const AssetsIdRouteChildren: AssetsIdRouteChildren = {
  AssetsIdEditRoute: AssetsIdEditRoute,
  AssetsIdIndexRoute: AssetsIdIndexRoute,
}

const AssetsIdRouteWithChildren = AssetsIdRoute._addFileChildren(
  AssetsIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  TypesRoute: TypesRouteWithChildren,
  AssetsIdRoute: AssetsIdRouteWithChildren,
  AssetsNewRoute: AssetsNewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
