/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AssetsNewRouteImport } from './routes/assets.new'
import { Route as AssetsIdRouteImport } from './routes/assets.$id'
import { Route as AssetsIdEditRouteImport } from './routes/assets.$id.edit'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AssetsNewRoute = AssetsNewRouteImport.update({
  id: '/assets/new',
  path: '/assets/new',
  getParentRoute: () => rootRouteImport,
} as any)
const AssetsIdRoute = AssetsIdRouteImport.update({
  id: '/assets/$id',
  path: '/assets/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AssetsIdEditRoute = AssetsIdEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => AssetsIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/assets/$id': typeof AssetsIdRouteWithChildren
  '/assets/new': typeof AssetsNewRoute
  '/assets/$id/edit': typeof AssetsIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/assets/$id': typeof AssetsIdRouteWithChildren
  '/assets/new': typeof AssetsNewRoute
  '/assets/$id/edit': typeof AssetsIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/assets/$id': typeof AssetsIdRouteWithChildren
  '/assets/new': typeof AssetsNewRoute
  '/assets/$id/edit': typeof AssetsIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/assets/$id' | '/assets/new' | '/assets/$id/edit'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/assets/$id' | '/assets/new' | '/assets/$id/edit'
  id: '__root__' | '/' | '/assets/$id' | '/assets/new' | '/assets/$id/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AssetsIdRoute: typeof AssetsIdRouteWithChildren
  AssetsNewRoute: typeof AssetsNewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assets/new': {
      id: '/assets/new'
      path: '/assets/new'
      fullPath: '/assets/new'
      preLoaderRoute: typeof AssetsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assets/$id': {
      id: '/assets/$id'
      path: '/assets/$id'
      fullPath: '/assets/$id'
      preLoaderRoute: typeof AssetsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assets/$id/edit': {
      id: '/assets/$id/edit'
      path: '/edit'
      fullPath: '/assets/$id/edit'
      preLoaderRoute: typeof AssetsIdEditRouteImport
      parentRoute: typeof AssetsIdRoute
    }
  }
}

interface AssetsIdRouteChildren {
  AssetsIdEditRoute: typeof AssetsIdEditRoute
}

const AssetsIdRouteChildren: AssetsIdRouteChildren = {
  AssetsIdEditRoute: AssetsIdEditRoute,
}

const AssetsIdRouteWithChildren = AssetsIdRoute._addFileChildren(
  AssetsIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AssetsIdRoute: AssetsIdRouteWithChildren,
  AssetsNewRoute: AssetsNewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
