/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TypesRouteImport } from './routes/types'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TypesIndexRouteImport } from './routes/types.index'
import { Route as TypesNewRouteImport } from './routes/types.new'
import { Route as TypesIdRouteImport } from './routes/types.$id'
import { Route as AssetsNewRouteImport } from './routes/assets.new'
import { Route as AssetsIdRouteImport } from './routes/assets.$id'
import { Route as TypesIdIndexRouteImport } from './routes/types.$id.index'
import { Route as AssetsIdIndexRouteImport } from './routes/assets.$id.index'
import { Route as TypesIdEditRouteImport } from './routes/types.$id.edit'
import { Route as AssetsIdEditRouteImport } from './routes/assets.$id.edit'

const TypesRoute = TypesRouteImport.update({
  id: '/types',
  path: '/types',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TypesIndexRoute = TypesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TypesRoute,
} as any)
const TypesNewRoute = TypesNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => TypesRoute,
} as any)
const TypesIdRoute = TypesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => TypesRoute,
} as any)
const AssetsNewRoute = AssetsNewRouteImport.update({
  id: '/assets/new',
  path: '/assets/new',
  getParentRoute: () => rootRouteImport,
} as any)
const AssetsIdRoute = AssetsIdRouteImport.update({
  id: '/assets/$id',
  path: '/assets/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const TypesIdIndexRoute = TypesIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TypesIdRoute,
} as any)
const AssetsIdIndexRoute = AssetsIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AssetsIdRoute,
} as any)
const TypesIdEditRoute = TypesIdEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => TypesIdRoute,
} as any)
const AssetsIdEditRoute = AssetsIdEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => AssetsIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/types': typeof TypesRouteWithChildren
  '/assets/$id': typeof AssetsIdRouteWithChildren
  '/assets/new': typeof AssetsNewRoute
  '/types/$id': typeof TypesIdRouteWithChildren
  '/types/new': typeof TypesNewRoute
  '/types/': typeof TypesIndexRoute
  '/assets/$id/edit': typeof AssetsIdEditRoute
  '/types/$id/edit': typeof TypesIdEditRoute
  '/assets/$id/': typeof AssetsIdIndexRoute
  '/types/$id/': typeof TypesIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/assets/new': typeof AssetsNewRoute
  '/types/new': typeof TypesNewRoute
  '/types': typeof TypesIndexRoute
  '/assets/$id/edit': typeof AssetsIdEditRoute
  '/types/$id/edit': typeof TypesIdEditRoute
  '/assets/$id': typeof AssetsIdIndexRoute
  '/types/$id': typeof TypesIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/types': typeof TypesRouteWithChildren
  '/assets/$id': typeof AssetsIdRouteWithChildren
  '/assets/new': typeof AssetsNewRoute
  '/types/$id': typeof TypesIdRouteWithChildren
  '/types/new': typeof TypesNewRoute
  '/types/': typeof TypesIndexRoute
  '/assets/$id/edit': typeof AssetsIdEditRoute
  '/types/$id/edit': typeof TypesIdEditRoute
  '/assets/$id/': typeof AssetsIdIndexRoute
  '/types/$id/': typeof TypesIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/types'
    | '/assets/$id'
    | '/assets/new'
    | '/types/$id'
    | '/types/new'
    | '/types/'
    | '/assets/$id/edit'
    | '/types/$id/edit'
    | '/assets/$id/'
    | '/types/$id/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/assets/new'
    | '/types/new'
    | '/types'
    | '/assets/$id/edit'
    | '/types/$id/edit'
    | '/assets/$id'
    | '/types/$id'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/types'
    | '/assets/$id'
    | '/assets/new'
    | '/types/$id'
    | '/types/new'
    | '/types/'
    | '/assets/$id/edit'
    | '/types/$id/edit'
    | '/assets/$id/'
    | '/types/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  TypesRoute: typeof TypesRouteWithChildren
  AssetsIdRoute: typeof AssetsIdRouteWithChildren
  AssetsNewRoute: typeof AssetsNewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/types': {
      id: '/types'
      path: '/types'
      fullPath: '/types'
      preLoaderRoute: typeof TypesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/types/': {
      id: '/types/'
      path: '/'
      fullPath: '/types/'
      preLoaderRoute: typeof TypesIndexRouteImport
      parentRoute: typeof TypesRoute
    }
    '/types/new': {
      id: '/types/new'
      path: '/new'
      fullPath: '/types/new'
      preLoaderRoute: typeof TypesNewRouteImport
      parentRoute: typeof TypesRoute
    }
    '/types/$id': {
      id: '/types/$id'
      path: '/$id'
      fullPath: '/types/$id'
      preLoaderRoute: typeof TypesIdRouteImport
      parentRoute: typeof TypesRoute
    }
    '/assets/new': {
      id: '/assets/new'
      path: '/assets/new'
      fullPath: '/assets/new'
      preLoaderRoute: typeof AssetsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assets/$id': {
      id: '/assets/$id'
      path: '/assets/$id'
      fullPath: '/assets/$id'
      preLoaderRoute: typeof AssetsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/types/$id/': {
      id: '/types/$id/'
      path: '/'
      fullPath: '/types/$id/'
      preLoaderRoute: typeof TypesIdIndexRouteImport
      parentRoute: typeof TypesIdRoute
    }
    '/assets/$id/': {
      id: '/assets/$id/'
      path: '/'
      fullPath: '/assets/$id/'
      preLoaderRoute: typeof AssetsIdIndexRouteImport
      parentRoute: typeof AssetsIdRoute
    }
    '/types/$id/edit': {
      id: '/types/$id/edit'
      path: '/edit'
      fullPath: '/types/$id/edit'
      preLoaderRoute: typeof TypesIdEditRouteImport
      parentRoute: typeof TypesIdRoute
    }
    '/assets/$id/edit': {
      id: '/assets/$id/edit'
      path: '/edit'
      fullPath: '/assets/$id/edit'
      preLoaderRoute: typeof AssetsIdEditRouteImport
      parentRoute: typeof AssetsIdRoute
    }
  }
}

interface TypesIdRouteChildren {
  TypesIdEditRoute: typeof TypesIdEditRoute
  TypesIdIndexRoute: typeof TypesIdIndexRoute
}

const TypesIdRouteChildren: TypesIdRouteChildren = {
  TypesIdEditRoute: TypesIdEditRoute,
  TypesIdIndexRoute: TypesIdIndexRoute,
}

const TypesIdRouteWithChildren =
  TypesIdRoute._addFileChildren(TypesIdRouteChildren)

interface TypesRouteChildren {
  TypesIdRoute: typeof TypesIdRouteWithChildren
  TypesNewRoute: typeof TypesNewRoute
  TypesIndexRoute: typeof TypesIndexRoute
}

const TypesRouteChildren: TypesRouteChildren = {
  TypesIdRoute: TypesIdRouteWithChildren,
  TypesNewRoute: TypesNewRoute,
  TypesIndexRoute: TypesIndexRoute,
}

const TypesRouteWithChildren = TypesRoute._addFileChildren(TypesRouteChildren)

interface AssetsIdRouteChildren {
  AssetsIdEditRoute: typeof AssetsIdEditRoute
  AssetsIdIndexRoute: typeof AssetsIdIndexRoute
}

const AssetsIdRouteChildren: AssetsIdRouteChildren = {
  AssetsIdEditRoute: AssetsIdEditRoute,
  AssetsIdIndexRoute: AssetsIdIndexRoute,
}

const AssetsIdRouteWithChildren = AssetsIdRoute._addFileChildren(
  AssetsIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  TypesRoute: TypesRouteWithChildren,
  AssetsIdRoute: AssetsIdRouteWithChildren,
  AssetsNewRoute: AssetsNewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
